inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  EnabledByDefault: true
  DefaultFormatter: fuubar
  TargetRubyVersion: 3.3

Style/MethodCallWithArgsParentheses:
  AllowedMethods:
    - describe
    - not_to
    - puts
    - raise
    - to

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren: { EnforcedStyle: compact }

Layout/LineLength:
  Max: 80

Lint/ConstantResolution: { Enabled: false }
Style/Copyright: { Enabled: false }
