# frozen_string_literal: true

# Generated by buttress. Fakes the I/O edges so the real code under
# test runs against controlled data: WebMock intercepts the network
# (every request succeeds with an empty body), and the config reader
# is pointed at a generated fixture.
require "webmock/rspec"

RSpec.configure do |config|
  config.before(:each, :buttress_io) do
    WebMock.disable_net_connect!
    WebMock.stub_request(:any, //).to_return(status: 200, body: "[]")
      Subsequent::TrelloClient.config_path = File.expand_path('../fixtures/buttress_config.yml', __dir__)
  end
end
