name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby
    strategy:
      matrix:
        ruby:
          - '3.4.1'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
    - uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage
        if-no-files-found: error
        include-hidden-files: true
